routes/web.php
Route::post('password/email', 'Admin\Auth\ForgotPasswordController@sendOTP')->name('password.email');
Route::get('password/otp', 'Admin\Auth\ForgotPasswordController@otpForm')->name('password.otp');
Route::get('password/otpvarify', 'Admin\Auth\ForgotPasswordController@otpVarification')->name('password.otpvarify');
Route::get('password/edit', 'Admin\Auth\ForgotPasswordController@passworUpdateForm')->name('password.edit');
Route::post('password/update', 'Admin\Auth\ForgotPasswordController@updatePassword')->name('password.update');

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => 'auth'], function () {

	Route::post('logout', 'Auth\LoginController@logout')->name('logout');

	Route::resource('dashboard', 'Dashboard\DashboardController');
	Route::get('dashboard/details/{id}/{param}', 'Dashboard\DashboardController@dashboardRequestDetails')->name('dashboard.details');

	Route::get('password', 'AdminController@password')->name('password');
	Route::post('password/update', 'AdminController@changePassword')->name('password.update');

	Route::get('profile', 'AdminController@profile')->name('profile');
	Route::post('profile/update', 'AdminController@profileUpdate')->name('profile.update');

	Route::resource('setting', 'Setting\SettingController');

	Route::get('privacy/policy', 'Setting\SettingController@privacyPolicy')->name('privacy.policy');
	Route::put('privacy-policy/update/{id}', 'Setting\SettingController@privacyPolicyUpdate')->name('privacy-policy.update');

	Route::get('privacy/policy/french', 'Setting\SettingController@privacyPolicyFrench')->name('privacy.policy.french');
	Route::put('privacy-policy/update/french/{id}', 'Setting\SettingController@privacyPolicyUpdateFrench')->name('privacy-policy.update.french');

	Route::get('safety/tools', 'Setting\SettingController@getSafetyTools')->name('safety.tools');
	Route::put('safety-tools/update/{id}', 'Setting\SettingController@updateSafetyTools')->name('safety-tools.update');

	Route::get('home/content', 'Setting\SettingController@homeContent')->name('home.content');
	Route::put('home-content/update/{id}', 'Setting\SettingController@homeContentUpdate')->name('home-content.update');

	Route::get('home/content/french', 'Setting\SettingController@homeContentFrench')->name('home.content.french');
	Route::put('home-content/update/french/{id}', 'Setting\SettingController@homeContentUpdateFrench')->name('home-content.update.french');


	Route::put('settings/femalefriendly', 'Setting\SettingController@femaleFriendlyUpdate')->name('settings.femalefriendly');
	Route::get('get/femalefriendly', 'Setting\SettingController@getFemaleFriendly')->name('get.femalefriendly');

	Route::resource('document', 'Document\DocumentController');
	Route::get('document/active/{id}', 'Document\DocumentController@changeStatus')->name('document.active');
	//preference
	Route::resource('preference', 'Preference\PreferenceController');
	Route::get('driver/preference/{id}', 'Preference\PreferenceController@driverPreferenceIndex');
	Route::post('driver/preference/get', 'Preference\PreferenceController@driverPreference')->name('driver.preference.get');
	Route::post('update/driver/preference', 'Preference\PreferenceController@updateDriverPreference')->name('update.driver.preference');


	Route::resource('emergency-assistance', 'EmergencyAssistance\EmergencyAssistanceController');

	//lease...
	Route::get('lease/hourly', 'Lease\LeaseController@hourlyLease')->name('lease.hourly');
	Route::get('lease/daily', 'Lease\LeaseController@dailyLease')->name('lease.daily');
	Route::get('lease/longTime', 'Lease\LeaseController@longTimeLease')->name('lease.longTime');
	Route::get('lease/view/{id}/{param}', 'Lease\LeaseController@showLeaseDetails')->name('lease.view');

	Route::resource('service', 'Service\ServiceTypeController');

	Route::resource('vehicle', 'Vehicle\VehicleController');
	Route::post('vehicles','Vehicle\VehicleController@getVehicles')->name('dataProcessing');

	Route::resource('passenger', 'Passenger\PassengerController');
	Route::post('ajax-passenger','Passenger\PassengerController@ajaxPassenger')->name('ajax-passenger');
	
	Route::get('get/vehicle', 'Driver\DriverController@getVehicle')->name('get.vehicle');

	Route::resource('driver', 'Driver\DriverController');
	Route::post('ajax-driver','Driver\DriverController@ajaxDriver')->name('ajax-driver');

	Route::get('drivers/document/{id}', 'Driver\DriverController@listDriverDocument')->name('drivers.document');
	Route::get('drivers/service-type/{id}', 'Driver\DriverController@listDriverServiceType')->name('drivers.service-type');
	Route::get('driver/document/verification/{id}', 'Driver\DriverController@driverDocumentVerification')->name('driver.document.verification');
	Route::get('driver/activation/{id}', 'Driver\DriverController@driverActivationProcess')->name('driver.activation');
	  //review rating
	Route::get('drivers/review-rating/{id}', 'Driver\DriverController@driverRatingReview')->name('drivers.review-rating');
	Route::get('passenger/review-rating/{id}', 'Passenger\PassengerController@passengerRatingReview')->name('passenger.review-rating');

	Route::put('drivers/femalefriendly', 'Driver\DriverController@isFemaleFriendly')->name('drivers.femalefriendly');

	//report
	Route::get('request/all', 'DriveReport\DriveReportController@allRequest')->name('request.all');
	Route::post('ajax-all-request', 'DriveReport\DriveReportController@ajaxAllRequest')->name('ajax-all-request');
	Route::get('request/nofound', 'DriveReport\DriveReportController@noServiceFoundRequest')->name('request.nofound');
	Route::post('ajax-noservice-found', 'DriveReport\DriveReportController@ajaxNoServiceFoundRequest')->name('ajax-noservice-found');

	Route::get('request/rejected', 'DriveReport\DriveReportController@rejectedRequest')->name('request.rejected');
	Route::post('ajax-rejected-request', 'DriveReport\DriveReportController@ajaxRejectedRequest')->name('ajax-rejected-request');

	Route::get('request/schedule', 'DriveReport\DriveReportController@scheduleRequest')->name('request.schedule');
	Route::post('ajax-schedule-request', 'DriveReport\DriveReportController@ajaxScheduleRequest')->name('ajax-schedule-request');

	Route::get('request/details/{id}/{param}', 'DriveReport\DriveReportController@requestDetails')->name('request.details');

	//chat support
	Route::get('passenger/chat/support', 'Chat\ChatSupportController@passengerChatSupport')->name('passenger.chat.support');

	Route::post('chat/message/support', 'Chat\ChatSupportController@sendChatForSupport')->name('chat.message.support');

	Route::post('chat/message/support/get', 'Chat\ChatSupportController@getChatForSupport')->name('chat.message.support.get');

	Route::get('driver/chat/support', 'Chat\ChatSupportController@driverChatSupport')->name('driver.chat.support');

	Route::get('driver/get/byid', 'Chat\ChatSupportController@getDriver')->name('driver.get.byid');
	Route::get('passenger/get/byid', 'Chat\ChatSupportController@getPassenger')->name('passenger.get.byid');

	//make model year
	Route::get('get/admin/make', 'Driver\DriverController@getAdminMake')->name("get.admin.make");
	Route::post('get/admin/model', 'Driver\DriverController@getAdminModel')->name("get.admin.model");
	Route::post('get/admin/year', 'Driver\DriverController@getAdminYear')->name("get.admin.year");

	 //passenger trip
	Route::get('passenger/trip/history/{id}', 'Passenger\TripController@tripIndex')->name("passenger.trip.history");
	Route::post('ajax-passenger-trips', 'Passenger\TripController@ajaxPassengerTrips')->name('ajax-passenger-trips');
	Route::get('passenger/trip/history/details/{id}/{param}', 'Passenger\TripController@tripDetails')->name('passenger.trip.history.details');

	 //Driver trip
	Route::get('driver/trip/history/{id}', 'Driver\DriverTripController@tripIndex')->name("driver.trip.history");
	Route::post('ajax-driver-trips', 'Driver\DriverTripController@ajaxDriverTrips')->name('ajax-driver-trips');
	Route::get('driver/trip/history/details/{id}/{param}', 'Driver\DriverTripController@tripDetails')->name('driver.trip.history.details');
	 //transaction
	Route::get('driver/transaction/{id}', 'Transaction\TransactionController@index')->name('driver.transaction');
	Route::post('driver/transaction', 'Transaction\TransactionController@transactionPayout')->name('driver.transaction');

	Route::get('passenger/transaction/{id}', 'Transaction\TransactionController@passengerTransaction')->name('passenger.transaction');
	Route::get('passenger/transac/list', 'Transaction\TransactionController@passengerTransactionList')->name('passenger.transac.list');

	Route::get('earning/report', 'Transaction\TransactionController@adminEarning')->name('earning.report');

	Route::resource('promocode', 'Promocode\PromocodeController');

	Route::get('passenger/cancel/report', 'CancelCharge\CancelChargeController@passengerCancelReport')->name('passenger.cancel.report');
	Route::get('driver/cancel/report', 'CancelCharge\CancelChargeController@driverCancelReport')->name('driver.cancel.report');

	// Route::get('driver/carimages/{id}', 'Driver\DriverController@driverCarImages')->name('driver.carimages');
	// Route::get('driver/transaction/{id}', 'Driver\DriverController@driverTransaction')->name('driver.transaction');
	// Route::post('driver/document-reason/{id}', 'Driver\DriverController@documentVerificationReason')->name('driver.document-reason');

	// Route::resource('credit', 'CreditPackage\CreditPackageController');
	// Route::resource('email-control', 'Email\EmailController');

	// //Driver Document verification.........

	// Route::get('driver/check-document/{id}', 'Driver\DocumentVerificationController@allDocumentCheck')->name('driver.check-document');
	// Route::get('driver/rating-review/{id}', 'Driver\DriverRatingController@driverRatingReview')->name('driver.rating-review');
	// Route::get('driver/runcron/{id}', 'Driver\DocumentVerificationController@cronjobToMailDriver')->name('driver.runcron');

app/Http/Controllers/Admin/Lease/LeaseController.php
<?php

namespace App\Http\Controllers\Admin\Lease;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Model\Leasing\Leasing;


class LeaseController extends Controller
{
    public function hourlyLease()
    {
        $leaseType='Hourly Lease';
        $leases = Leasing::join('service_types','leasing.services_type_id','=','service_types.id')
            ->join('passengers_profile','leasing.passenger_id','=','passengers_profile.user_id')
            ->select('leasing.*', 'service_types.name as service_name', 'passengers_profile.first_name as first_name','passengers_profile.last_name as last_name','passengers_profile.user_id as user_id')
            ->where('leasing.lease_type','hourly')
            ->orderBy('leasing.leasing_id', 'desc')
            ->get();
        if (isset($leases)){
            return view('admin.lease.lease',compact('leases','leaseType'));
        } else {
            return redirect()->back()->with('flash_error', 'Hourly lease not found!');
        }
    
    }

    public function dailyLease()
    {
        $leaseType='Daily Lease';
        $leases = Leasing::join('service_types','leasing.services_type_id','=','service_types.id')
            ->join('passengers_profile','leasing.passenger_id','=','passengers_profile.user_id')
            ->select('leasing.*', 'service_types.name as service_name', 'passengers_profile.first_name as first_name','passengers_profile.last_name as last_name','passengers_profile.user_id as user_id')
            ->where('leasing.lease_type','daily')
            ->orderBy('leasing.leasing_id', 'desc')
            ->get();

        if (isset($leases)){
            return view('admin.lease.lease',compact('leases','leaseType'));
        } else {
            return redirect()->back()->with('flash_error', 'Daily lease not found!');
        }

    }

    public function longTimeLease()
    {
        $leaseType='Long-Term Lease';
        $leases = Leasing::join('service_types','leasing.services_type_id','=','service_types.id')
            ->join('passengers_profile','leasing.passenger_id','=','passengers_profile.user_id')
            ->select('leasing.*', 'service_types.name as service_name', 'passengers_profile.first_name as first_name','passengers_profile.last_name as last_name','passengers_profile.user_id as user_id')
            ->where('leasing.lease_type','longTime')
            ->orderBy('leasing.leasing_id', 'desc')
            ->get();

        if (isset($leases)){
            return view('admin.lease.lease',compact('leases','leaseType'));
        } else {
            return redirect()->back()->with('flash_error', 'Long time lease not found!');
        }

    }

    public function showLeaseDetails($leasing_id,$param)
    {
        if ($param=='hourly') {
            $leaseType='Hourly Lease';
        }
        if ($param=='daily') {
            $leaseType='Daily Lease';
        }
        if ($param=='longTime') {
            $leaseType='Long-Term Lease';
        }
        
        $lease = Leasing::join('service_types','leasing.services_type_id','=','service_types.id')
            ->join('passengers_profile','leasing.passenger_id','=','passengers_profile.user_id')
            ->select('service_types.name as service_name','leasing.no_passenger','leasing.address','leasing.vehicle_equipment','leasing.services_type_id','leasing.to_datetime','leasing.from_datetime','leasing.dateOfJourny','leasing.details','leasing.leasing_id','passengers_profile.*')
            ->where('leasing.leasing_id',$leasing_id)
            ->first();
        
        return view('admin.lease.lease-details',compact('lease','param','leaseType'));

    }
}

resources/views/admin/lease/lease-details.blade.php
@extends('admin.layout.base')

@section('title', $leaseType)

@section('content')
<div class="content-area py-1">
    <div class="container-fluid">
        <div class="box box-block bg-white">
            @if($param=='daily')
            <a href="{{ route('admin.lease.daily') }}" style="margin-left: 1em;" class="btn btn-default pull-right"><i class="fa fa-angle-left"></i> Back</a>
            @endif
            @if($param=='hourly')
            <a href="{{ route('admin.lease.hourly') }}" style="margin-left: 1em;" class="btn btn-default pull-right"><i class="fa fa-angle-left"></i> Back</a>
            @endif
            @if($param=='longTime')
            <a href="{{ route('admin.lease.longTime') }}" style="margin-left: 1em;" class="btn btn-default pull-right"><i class="fa fa-angle-left"></i> Back</a>
            @endif
            <h4 style="margin-bottom: 1em;">{{$leaseType}}</h4>

            <div class="row">
                <div class="col-md-8">
                    <h4 class="text-info">Customer Details:</h4>
                    <dl class="row">
                        <dt class="col-sm-4">Customer Name :</dt>
                        <dd class="col-sm-8">
                           {{$lease->first_name}} {{$lease->last_name}}
                        </dd>

                        <dt class="col-sm-4">Email ID :</dt>
                        <dd class="col-sm-8">
                            {{$lease->email_id}}
                        </dd>

                        <dt class="col-sm-4">Contact No. :</dt>
                        <dd class="col-sm-8">
                            {{$lease->isd_code}}-{{$lease->mobile_no}}
                        </dd>
                    </dl>
                    <h4 class="text-info">Lease Details:</h4>
                    <dl class="row">

                        @if($param=='hourly')
                        <dt class="col-sm-4">Date of Journey :</dt>
                        <dd class="col-sm-8">
                          {{$lease->dateOfJourny}}
                        </dd>
                        <dt class="col-sm-4">Time :</dt>
                        <dd class="col-sm-8">
                          {{date('h:i A',strtotime($lease->from_datetime))}} to {{date('h:i A',strtotime($lease->to_datetime))}}
                        </dd>
                        <dt class="col-sm-4">Pickup Address :</dt>
                        <dd class="col-sm-8">
                            {{$lease->address}}
                        </dd>
                        <dt class="col-sm-4">No of Passenger :</dt>
                        <dd class="col-sm-8">
                            {{$lease->no_passenger}}
                        </dd>
                         @endif

                        @if($param=='daily')
                        <dt class="col-sm-4">Date of Journey :</dt>
                        <dd class="col-sm-8">
                          {{$lease->dateOfJourny}}
                        </dd>
                        <dt class="col-sm-4">Pickup Address :</dt>
                        <dd class="col-sm-8">
                            {{$lease->address}}
                        </dd>
                        <dt class="col-sm-4">No of Passenger :</dt>
                        <dd class="col-sm-8">
                            {{$lease->no_passenger}}
                        </dd>
                        @endif

                        @if($param=='longTime')
                        <dt class="col-sm-4">Date :</dt>
                        <dd class="col-sm-8">
                          {{date('Y-m-d',strtotime($lease->from_datetime))}} to {{date('Y-m-d',strtotime($lease->to_datetime))}}
                        </dd>
                        <dt class="col-sm-4">Pickup Address :</dt>
                        <dd class="col-sm-8">
                            {{$lease->address}}
                        </dd>
                        @endif

                        <dt class="col-sm-4">Service Type :</dt>
                        <dd class="col-sm-8">
                            {{$lease->service_name}}
                        </dd>
                        @if($lease->services_type_id==4)
                        <dt class="col-sm-4">V/E Details :</dt>
                        <dd class="col-sm-8">
                            {{$lease->vehicle_equipment}}
                        </dd>
                        @endif
                        <dt class="col-sm-4">Other Details :</dt>
                        <dd class="col-sm-8">
                            {{$lease->details}}
                        </dd>
                       
                    </dl>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/lease/lease.blade.php
@extends('admin.layout.base')

@section('title', $leaseType)

@section('content')

    <div class="content-area py-1">
        <div class="container-fluid">
            
            <div class="box box-block bg-white">
                <h5 class="mb-1">{{$leaseType}}</h5>
                <table class="table table-striped table-bordered dataTable" id="table-2">
                    <thead>
                        <tr>
                            <th>S.No</th>
                            <th>Customer Name</th>
                            <th>Service Name</th>
                            <th>Address</th>
                            @if($leaseType=='Hourly Lease')
                            <th>Date of Journey</th>
                            <th>From Time</th>
                            <th>To Time</th>
                            <th>No. of Passenger</th>
                            @endif
                            @if($leaseType=='Daily Lease')
                            <th>Date of Journey</th>
                            <th>No. of Passenger</th>
                            @endif
                            @if($leaseType=='Long-Term Lease')
                            <th>From Date</th>
                            <th>To Date</th>
                            @endif
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                    @foreach($leases as $index => $lease)
                        <tr>
                            <td>{{$index + 1}}</td>
                            <td>{{$lease->first_name}} {{$lease->last_name}}</td>
                            <td>{{$lease->service_name}}</td>
                            <td>{{$lease->address}}</td>
                            @if($leaseType=='Hourly Lease')
                            <th>{{date('d M, Y',strtotime($lease->dateOfJourny))}}</th>
                            <td>{{date('h:i A',strtotime($lease->from_datetime))}}</td>
                            <td>{{date('h:i A',strtotime($lease->to_datetime))}}</td>
                            <td>{{$lease->no_passenger}}</td>
                            @endif
                            @if($leaseType=='Daily Lease')
                            <th>{{date('d M, Y',strtotime($lease->dateOfJourny))}}</th>
                             <td>{{$lease->no_passenger}}</td>
                            @endif
                            @if($leaseType=='Long-Term Lease')
                            <td>{{date('d M, Y',strtotime($lease->from_datetime))}}</td>
                            <td>{{date('d M, Y',strtotime($lease->to_datetime))}}</td>
                            @endif
                            
                            <td style="line-height: 33px;">
                                <a href="{{ route('admin.lease.view', [$lease->leasing_id,$lease->lease_type]) }}" class="btn btn-info">View</a>
                                @php
                                    $arrayName = array('lease'=>'lease','user'=>$lease->user_id);
                                    $encodeData = json_encode($arrayName);
                                    $param = encrypt($encodeData);
                                @endphp
                                <a href="{{ route('admin.passenger.chat.support') }}?param={{$param}}" class="btn btn-info"><i class="far fa-comment-dots"> Chat</i>
                                </a>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                    <tfoot>
                        <tr>
                            <th>S.No</th>
                            <th>Customer Name</th>
                            <th>Service Name</th>
                            <th>Address</th>
                            @if($leaseType=='Hourly Lease')
                            <th>Date of Journey</th>
                            <th>From Time</th>
                            <th>To Time</th>
                            <th>No. of Passenger</th>
                            @endif
                            @if($leaseType=='Daily Lease')
                            <th>Date of Journey</th>
                            <th>No. of Passenger</th>
                            @endif
                            @if($leaseType=='Long-Term Lease')
                            <th>From Date</th>
                            <th>To Date</th>
                            @endif
                    
                            <th>Action</th>
                        </tr>
                    </tfoot>
                </table>
            </div>
            
        </div>
    </div>
@endsection